/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IF.JFrames;

import java.awt.*;

/**
 * @author SammyLaptop
 */
public class NewJFrame extends javax.swing.JFrame implements OSRSForm
{

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton           jButton1;
    private javax.swing.JCheckBox         jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane      jDesktopPane1;
    private javax.swing.JLabel            jLabel1;
    private javax.swing.JLabel            jLabel10;
    private javax.swing.JLabel            jLabel11;
    private javax.swing.JLabel            jLabel12;
    private javax.swing.JLabel            jLabel13;
    private javax.swing.JLabel            jLabel14;
    private javax.swing.JLabel            jLabel15;
    private javax.swing.JLabel            jLabel16;
    private javax.swing.JLabel            jLabel17;
    private javax.swing.JLabel            jLabel18;
    private javax.swing.JLabel            jLabel19;
    private javax.swing.JLabel            jLabel2;
    private javax.swing.JLabel            jLabel20;
    private javax.swing.JLabel            jLabel21;
    private javax.swing.JLabel            jLabel22;
    private javax.swing.JLabel            jLabel23;
    private javax.swing.JLabel            jLabel24;
    private javax.swing.JLabel            jLabel25;
    private javax.swing.JLabel            jLabel26;
    private javax.swing.JLabel            jLabel27;
    private javax.swing.JLabel            jLabel28;
    private javax.swing.JLabel            jLabel29;
    private javax.swing.JLabel            jLabel3;
    private javax.swing.JLabel            jLabel30;
    private javax.swing.JLabel            jLabel31;
    private javax.swing.JLabel            jLabel4;
    private javax.swing.JLabel            jLabel5;
    private javax.swing.JLabel            jLabel6;
    private javax.swing.JLabel            jLabel7;
    private javax.swing.JLabel            jLabel8;
    private javax.swing.JLabel            jLabel9;
    private javax.swing.JList<String>     jList1;
    private javax.swing.JList<String>     jList2;
    private javax.swing.JList<String>     jList3;
    private javax.swing.JPanel            jPanel1;
    private javax.swing.JPanel            jPanel2;
    private javax.swing.JScrollPane       jScrollPane1;
    private javax.swing.JScrollPane       jScrollPane2;
    private javax.swing.JScrollPane       jScrollPane3;
    private javax.swing.JSplitPane        jSplitPane2;
    private javax.swing.JTabbedPane       jTabbedPane1;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1  = new javax.swing.JTabbedPane();
        jSplitPane2   = new javax.swing.JSplitPane();
        jPanel1       = new javax.swing.JPanel();
        jLabel1       = new javax.swing.JLabel();
        jLabel2       = new javax.swing.JLabel();
        jLabel3       = new javax.swing.JLabel();
        jLabel4       = new javax.swing.JLabel();
        jLabel5       = new javax.swing.JLabel();
        jLabel6       = new javax.swing.JLabel();
        jLabel7       = new javax.swing.JLabel();
        jLabel17      = new javax.swing.JLabel();
        jLabel13      = new javax.swing.JLabel();
        jLabel8       = new javax.swing.JLabel();
        jLabel16      = new javax.swing.JLabel();
        jLabel18      = new javax.swing.JLabel();
        jLabel14      = new javax.swing.JLabel();
        jLabel9       = new javax.swing.JLabel();
        jLabel22      = new javax.swing.JLabel();
        jLabel11      = new javax.swing.JLabel();
        jLabel10      = new javax.swing.JLabel();
        jLabel15      = new javax.swing.JLabel();
        jLabel20      = new javax.swing.JLabel();
        jLabel19      = new javax.swing.JLabel();
        jLabel21      = new javax.swing.JLabel();
        jLabel12      = new javax.swing.JLabel();
        jLabel23      = new javax.swing.JLabel();
        jLabel24      = new javax.swing.JLabel();
        jLabel25      = new javax.swing.JLabel();
        jLabel26      = new javax.swing.JLabel();
        jLabel27      = new javax.swing.JLabel();
        jPanel2       = new javax.swing.JPanel();
        jScrollPane1  = new javax.swing.JScrollPane();
        jList1        = new javax.swing.JList<>();
        jLabel28      = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1      = new javax.swing.JButton();
        jScrollPane2  = new javax.swing.JScrollPane();
        jList2        = new javax.swing.JList<>();
        jLabel29      = new javax.swing.JLabel();
        jCheckBox1    = new javax.swing.JCheckBox();
        jComboBox1    = new javax.swing.JComboBox<>();
        jLabel30      = new javax.swing.JLabel();
        jScrollPane3  = new javax.swing.JScrollPane();
        jList3        = new javax.swing.JList<>();
        jLabel31      = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,
                                                                                            0,
                                                                                            0)));
        jSplitPane2.setDividerLocation(300);
        jSplitPane2.setDividerSize(1);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(9, 3));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/icons/Skills/Attack_icon_(detail).png"))); // NOI18N
        jLabel1.setText("0 / 99");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setName(""); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("");

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("0 / 99");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setName(""); // NOI18N
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleName("");

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("0 / 99");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setName(""); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.getAccessibleContext().setAccessibleName("");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0 / 99");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setName(""); // NOI18N
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.getAccessibleContext().setAccessibleName("");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("0 / 99");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setName(""); // NOI18N
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.getAccessibleContext().setAccessibleName("");

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0 / 99");
        jLabel6.setAlignmentX(0.5F);
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setName(""); // NOI18N
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.getAccessibleContext().setAccessibleName("");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("0 / 99");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setName(""); // NOI18N
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.getAccessibleContext().setAccessibleName("");

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("0 / 99");
        jLabel17.setAlignmentX(0.5F);
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel17.setName(""); // NOI18N
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17);
        jLabel17.getAccessibleContext().setAccessibleName("");

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("0 / 99");
        jLabel13.setAlignmentX(0.5F);
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setName(""); // NOI18N
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13);
        jLabel13.getAccessibleContext().setAccessibleName("");

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("0 / 99");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setName(""); // NOI18N
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.getAccessibleContext().setAccessibleName("");

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("0 / 99");
        jLabel16.setAlignmentX(0.5F);
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setName(""); // NOI18N
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16);
        jLabel16.getAccessibleContext().setAccessibleName("");

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("0 / 99");
        jLabel18.setAlignmentX(0.5F);
        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18.setName(""); // NOI18N
        jLabel18.setOpaque(true);
        jPanel1.add(jLabel18);
        jLabel18.getAccessibleContext().setAccessibleName("");

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("0 / 99");
        jLabel14.setAlignmentX(0.5F);
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setName(""); // NOI18N
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14);
        jLabel14.getAccessibleContext().setAccessibleName("");

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("0 / 99");
        jLabel9.setAlignmentX(0.5F);
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setName(""); // NOI18N
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.getAccessibleContext().setAccessibleName("");

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("0 / 99");
        jLabel22.setAlignmentX(0.5F);
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22.setName(""); // NOI18N
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22);
        jLabel22.getAccessibleContext().setAccessibleName("");

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("0 / 99");
        jLabel11.setAlignmentX(0.5F);
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setName(""); // NOI18N
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11);
        jLabel11.getAccessibleContext().setAccessibleName("");

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("0 / 99");
        jLabel10.setAlignmentX(0.5F);
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setName(""); // NOI18N
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10);
        jLabel10.getAccessibleContext().setAccessibleName("");

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("0 / 99");
        jLabel15.setAlignmentX(0.5F);
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.setName(""); // NOI18N
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15);
        jLabel15.getAccessibleContext().setAccessibleName("");

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("0 / 99");
        jLabel20.setAlignmentX(0.5F);
        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel20.setName(""); // NOI18N
        jLabel20.setOpaque(true);
        jPanel1.add(jLabel20);
        jLabel20.getAccessibleContext().setAccessibleName("");

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("0 / 99");
        jLabel19.setAlignmentX(0.5F);
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel19.setName(""); // NOI18N
        jLabel19.setOpaque(true);
        jPanel1.add(jLabel19);
        jLabel19.getAccessibleContext().setAccessibleName("");

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("0 / 99");
        jLabel21.setAlignmentX(0.5F);
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel21.setName(""); // NOI18N
        jLabel21.setOpaque(true);
        jPanel1.add(jLabel21);
        jLabel21.getAccessibleContext().setAccessibleName("");

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("0 / 99");
        jLabel12.setAlignmentX(0.5F);
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setName(""); // NOI18N
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12);
        jLabel12.getAccessibleContext().setAccessibleName("");

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("0 / 99");
        jLabel23.setAlignmentX(0.5F);
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel23.setName(""); // NOI18N
        jLabel23.setOpaque(true);
        jPanel1.add(jLabel23);
        jLabel23.getAccessibleContext().setAccessibleName("");

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("0 / 99");
        jLabel24.setAlignmentX(0.5F);
        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel24.setName(""); // NOI18N
        jLabel24.setOpaque(true);
        jPanel1.add(jLabel24);
        jLabel24.getAccessibleContext().setAccessibleName("");

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("0 / 99");
        jLabel25.setAlignmentX(0.5F);
        jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel25.setName(""); // NOI18N
        jLabel25.setOpaque(true);
        jPanel1.add(jLabel25);
        jLabel25.getAccessibleContext().setAccessibleName("");

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("0 / 99");
        jLabel26.setAlignmentX(0.5F);
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel26.setName(""); // NOI18N
        jLabel26.setOpaque(true);
        jPanel1.add(jLabel26);
        jLabel26.getAccessibleContext().setAccessibleName("");

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("0 / 99");
        jLabel27.setAlignmentX(0.5F);
        jLabel27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel27.setName(""); // NOI18N
        jLabel27.setOpaque(true);
        jPanel1.add(jLabel27);
        jLabel27.getAccessibleContext().setAccessibleName("");

        jSplitPane2.setLeftComponent(jPanel1);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            final String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jList1);

        jLabel28.setText("Activities");

        jButton1.setText("Config");

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jList2.setModel(new javax.swing.AbstractListModel<String>()
        {
            final String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jList2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jList2);

        jLabel29.setText("Requirements");

        jCheckBox1.setText("Enabled");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
                "Count", "Endless", "Goal", "Natural End", " "}));

        jLabel30.setText("Goal Type");

        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                  .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                                                               .addContainerGap()
                                                                                               .addGroup(
                                                                                                       jDesktopPane1Layout.createParallelGroup(
                                                                                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                          .addComponent(
                                                                                                                                  jLabel29,
                                                                                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                  100,
                                                                                                                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                          .addGroup(
                                                                                                                                  jDesktopPane1Layout.createSequentialGroup()
                                                                                                                                                     .addComponent(
                                                                                                                                                             jScrollPane2,
                                                                                                                                                             javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                             169,
                                                                                                                                                             javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                     .addPreferredGap(
                                                                                                                                                             javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                     .addGroup(
                                                                                                                                                             jDesktopPane1Layout.createParallelGroup(
                                                                                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                        false)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                        jButton1,
                                                                                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                        jCheckBox1,
                                                                                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                        jComboBox1,
                                                                                                                                                                                        0,
                                                                                                                                                                                        115,
                                                                                                                                                                                        Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                        jLabel30,
                                                                                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                        Short.MAX_VALUE))))
                                                                                               .addContainerGap(
                                                                                                       255,
                                                                                                       Short.MAX_VALUE)));
        jDesktopPane1Layout.setVerticalGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                                                             .addContainerGap()
                                                                                             .addComponent(
                                                                                                     jLabel29)
                                                                                             .addPreferredGap(
                                                                                                     javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                             .addGroup(
                                                                                                     jDesktopPane1Layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                        .addComponent(
                                                                                                                                jScrollPane2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                138,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                        .addGroup(
                                                                                                                                jDesktopPane1Layout.createSequentialGroup()
                                                                                                                                                   .addComponent(
                                                                                                                                                           jButton1)
                                                                                                                                                   .addPreferredGap(
                                                                                                                                                           javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                   .addComponent(
                                                                                                                                                           jCheckBox1)
                                                                                                                                                   .addGap(11,
                                                                                                                                                           11,
                                                                                                                                                           11)
                                                                                                                                                   .addComponent(
                                                                                                                                                           jLabel30)
                                                                                                                                                   .addPreferredGap(
                                                                                                                                                           javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                   .addComponent(
                                                                                                                                                           jComboBox1,
                                                                                                                                                           javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                           javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                           javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                             .addContainerGap(
                                                                                                     46,
                                                                                                     Short.MAX_VALUE)));

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jList3.setModel(new javax.swing.AbstractListModel<String>()
        {
            final String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jList3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(jList3);

        jLabel31.setText("Task list");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(jPanel2Layout.createSequentialGroup()
                                                                             .addGap(26, 26, 26)
                                                                             .addGroup(jPanel2Layout.createParallelGroup(
                                                                                                            javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                            false)
                                                                                                    .addComponent(
                                                                                                            jLabel31,
                                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                            100,
                                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                    .addComponent(
                                                                                                            jDesktopPane1)
                                                                                                    .addComponent(
                                                                                                            jScrollPane1)
                                                                                                    .addComponent(
                                                                                                            jLabel28,
                                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                            100,
                                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                    .addComponent(
                                                                                                            jScrollPane3))
                                                                             .addContainerGap(65,
                                                                                              Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                                           .addGap(21, 21, 21)
                                                                           .addComponent(jLabel28)
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                           .addComponent(
                                                                                   jScrollPane1,
                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                   138,
                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                           .addComponent(
                                                                                   jDesktopPane1,
                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                   javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                            19,
                                                                                            Short.MAX_VALUE)
                                                                           .addComponent(jLabel31)
                                                                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                           .addComponent(
                                                                                   jScrollPane3,
                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                   138,
                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE)));

        jSplitPane2.setRightComponent(jPanel2);

        jTabbedPane1.addTab("tab1", jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTabbedPane1,
                                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                      944,
                                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(layout.createSequentialGroup()
                                                      .addComponent(jTabbedPane1,
                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                    615,
                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // End of variables declaration//GEN-END:variables

    @Override
    public Container GetForm()
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
