/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IF.JFrames;

import IF.Utilities.Patterns.Delegates.Delegate;
import IF.Utilities.Patterns.Delegates.Delegate1;
import IF.Utilities.Scripting.Annotations.ScriptMetadata;
import IF.Utilities.Scripting.IFScript;
import IF.Utilities.Scripting.Logger;

import java.awt.*;
import java.util.Collection;

/**
 * @author SammyLaptop
 */
public class ScriptSelector extends javax.swing.JPanel implements OSRSForm
{
    public Delegate1<Class<? extends IFScript>> onProceed = new Delegate1<>();
    public Delegate                             onExit    = new Delegate();

    public class ClassWrapper
    {
        public Class<? extends IFScript> klass;

        public ClassWrapper(Class<? extends IFScript> klass)
        {
            this.klass = klass;
        }

        @Override
        public String toString()
        {
            ScriptMetadata metadata = klass.getAnnotation(ScriptMetadata.class);
            if(metadata != null)
            {
                return metadata.Name();
            }
            return klass.getName();
        }
    }

    /**
     * Creates new form ScriptSelector
     */
    public ScriptSelector()
    {
        initComponents();
    }

    @Override
    public Container GetForm()
    {
        return this;
    }


    public void SetListData(Collection<Class<? extends IFScript>> classes)
    {
        ScriptList.setListData(classes.stream()
                                      .map((t) -> new ClassWrapper(t))
                                      .toArray(ClassWrapper[]::new));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1           = new javax.swing.JScrollPane();
        ScriptList             = new javax.swing.JList<>();
        EnterButton            = new javax.swing.JButton();
        jScrollPane2           = new javax.swing.JScrollPane();
        ScriptNameField        = new javax.swing.JTextPane();
        jScrollPane3           = new javax.swing.JScrollPane();
        ScriptDescriptionField = new javax.swing.JTextPane();
        CancelButton           = new javax.swing.JButton();

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ScriptList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ScriptList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                ScriptListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ScriptList);

        EnterButton.setText("Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EnterButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(ScriptNameField);

        jScrollPane3.setViewportView(ScriptDescriptionField);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addComponent(jScrollPane1,
                                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                      231,
                                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(
                                                                                                CancelButton)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                7,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(
                                                                                                EnterButton))
                                                                        .addComponent(jScrollPane2)
                                                                        .addComponent(jScrollPane3))
                                                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                      .addGroup(layout.createSequentialGroup()
                                                                                      .addComponent(
                                                                                              jScrollPane2,
                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                      .addPreferredGap(
                                                                                              javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                      .addComponent(
                                                                                              jScrollPane3,
                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                              153,
                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                      .addPreferredGap(
                                                                                              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                              84,
                                                                                              Short.MAX_VALUE)
                                                                                      .addGroup(
                                                                                              layout.createParallelGroup(
                                                                                                            javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                    .addComponent(
                                                                                                            EnterButton)
                                                                                                    .addComponent(
                                                                                                            CancelButton)))
                                                                      .addComponent(jScrollPane1))
                                                      .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_EnterButtonActionPerformed
        var value = ScriptList.getSelectedValue();
        Logger.log("EnterButtonActionPerformed: "  + value.klass);
        if(value != null && value.klass != null)
        {
            onProceed.Fire(value.klass);
        }
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_CancelButtonActionPerformed
        onExit.Fire();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ScriptListValueChanged(javax.swing.event.ListSelectionEvent evt)
    {//GEN-FIRST:event_ScriptListValueChanged
        var value = ScriptList.getSelectedValue();
        if(value != null && value.klass != null)
        {
            ScriptMetadata metadata = value.klass.getAnnotation(ScriptMetadata.class);
            if(metadata != null)
            {
                ScriptNameField.setText(metadata.Name());
                ScriptDescriptionField.setText(metadata.Description());
            }
            EnterButton.setEnabled(true);

        }
        else
        {
            EnterButton.setEnabled(false);
        }
    }//GEN-LAST:event_ScriptListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ScriptSelector.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ScriptSelector.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ScriptSelector.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ScriptSelector.class.getName())
                                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ScriptSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton             CancelButton;
    private javax.swing.JButton             EnterButton;
    private javax.swing.JTextPane           ScriptDescriptionField;
    private javax.swing.JList<ClassWrapper> ScriptList;
    private javax.swing.JTextPane           ScriptNameField;
    private javax.swing.JScrollPane         jScrollPane1;
    private javax.swing.JScrollPane         jScrollPane2;
    private javax.swing.JScrollPane         jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
